# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Team-Panda' do
  use_frameworks!

  # Pods for Team-Panda
  pod 'Alamofire', '~> 4.0'
  pod 'ChameleonFramework/Swift'
  pod 'SwiftFontName', '~> 2.0.0'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'SwiftyButton'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SWXMLHash'
  pod 'SwiftSpinner'
  pod 'Font-Awesome-Swift', '~> 1.5.3'

end