# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Team-Panda' do
  use_frameworks!

  # Pods for Team-Panda
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'ChameleonFramework/Swift'
  pod 'SwiftFontName', '~> 2.0.0'
  pod 'SwiftyButton'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod "Former"
  pod 'USStatesColorMap', '1.0.0'

  target 'Team-PandaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Team-PandaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end